name: Dependabot

on:
  schedule:
    - cron: '0 0 * * 5'
  workflow_dispatch:

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - uses: actions/checkout@v3
      - run: pnpx npm-check-updates -u
      - run: pnpm i --no-frozen-lockfile

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
